# -*- coding: utf-8 -*-
"""primenumbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17POFwjfaxxGcZ1_1SAcwkZR-g3Bl8VGf
"""

n = int(input("enter a number to check if it is a prime number"))
count = 0
for i in range(1,n+1):
  if n % i == 0:
    count +=1
if (n==0) or (n==1) or (count>=3):
  print(n,"is not a prime number")
else:
  print(n,"is a primenumber ")